version: '3.8'

services:
  ut-se-message-jms:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - activemq
    volumes:
      - .:/app

  activemq:
    image: apache/activemq-artemis:latest
    user: root
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
